import Head from 'next/head';
import Body from '@components/layouts/Body';
import Main from '@components/layouts/Main';
import MainPhotoCardGallery from '@components/gallery/MainPhotoCardGallery';
import FloatingButton from '@components/buttons/Floating';
import drive from '@pages/api/drive';
import styles from '@styles/Gallery.module.css';
/**
 * @function: getServerSideProps.
 * @description: obtains all information about pets.
 * @returns: returns an array of objects with all the pet information.
 */
export const getServerSideProps = async () => {
  const petsArray = await drive.getAllPetsInformation();
  return { props: { petsArray } };
};
// --
export default function CategoriesPage(props) {
  const { petsArray } = props;
  return (
    <>
      <Head>
        <title>Petgram - Team Collaboration Software</title>
        <meta name='Description' content='Generated by create next app' />
      </Head>
      <Body>
        <main className={styles.main}>
          <Main>
            <MainPhotoCardGallery params={{ petsArray }} />
          </Main>
        </main>
      </Body>
      <FloatingButton params={{ trigger: 'click', href: '/', visibilityHeight: 500 }} />
    </>
  );
}
