import Head from 'next/head';
import Header from '@components/headers/Header';
import Main from '@components/layouts/Main';
import drive from '@pages/api/drive';
import MainPhotoCardGallery from '@components/gallery/MainPhotoCardGallery';
import FloatingButton from '@components/buttons/Floating';
import styles from '@styles/Gallery.module.css';
/**
 * @function: getServerSideProps.
 * @description: obtains all information about pets.
 * @returns: returns an array of objects with all the pet information.
 */
export const getServerSideProps = async () => {
  const petsArray = await drive.getAllPetsInformation();
  return { props: { petsArray } };
};
// --
export default function CategoriesPage(props) {
  const { petsArray } = props;
  return (
    <>
      <Head>
        <title>Petgram - Team Collaboration Software</title>
        <meta name='Description' content='Generated by create next app' />
      </Head>
      <header className={styles.header}>
        <Header />
      </header>
      <main className={styles.main}>
        <Main>
          <MainPhotoCardGallery params={{ petsArray }} />
        </Main>
      </main>
      <FloatingButton params={{ trigger: 'click', href: '/', visibilityHeight: 500 }} />
    </>
  );
}
