import Head from 'next/head';
import Body from '@components/layouts/Body';
import Main from '@components/layouts/Main';
import File from '@components/details/File';
import FloatingButton from '@components/buttons/Floating';
import drive from '@pages/api/drive';
/**
 * @function: getServerSideProps.
 * @description: obtain all information about pet.
 * @returns: returns an array of objects with all the pet information.
 */
export const getServerSideProps = async ({ params }) => {
  const pet = await drive.getPetInformation(params.pet_id);
  return { props: { pet } };
};
// --
export default function PetDetails(props) {
  console.log('----------->ok>', props);
  return (
    <>
      <Head>
        <title>Petgram - Team Collaboration Software</title>
        <meta name='Description' content='Generated by create next app' />
      </Head>
      <Body>
        <main>
          <Main>
            <File />
          </Main>
        </main>
      </Body>
      <FloatingButton params={{ trigger: 'click', href: '/', visibilityHeight: 100 }} />
    </>
  );
}
