import Head from 'next/head';
import Header from '@components/headers/Header';
import Main from '@components/layouts/Main';
import File from '@components/details/File';
import FloatingButton from '@components/buttons/Floating';
// --
export default function PetDetails() {
  return (
    <>
      <Head>
        <title>Petgram - Team Collaboration Software</title>
        <meta name='Description' content='Generated by create next app' />
      </Head>
      <header>
        <Header />
      </header>
      <main>
        <Main>
          <File />
        </Main>
      </main>
      <FloatingButton params={{ trigger: 'click', href: '/', visibilityHeight: 100 }} />
    </>
  );
}
